//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentCode
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public bool AffectsDemand { get; set; }
        public bool Use { get; set; }
        public bool IsSystem { get; set; }
    }
}
