//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryUnit
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public int LotNumber { get; set; }
        public string ReceiveReceipt { get; set; }
        public string ReceiveAdjustment { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string IssueReceipt { get; set; }
        public string IssueAdjustment { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public decimal UnitQuantity { get; set; }
        public decimal PackageQuantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Total { get; set; }
        public decimal NetWeight { get; set; }
        public decimal GrossWeight { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool IsHold { get; set; }
        public string Remark { get; set; }
        public string Notes { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<int> AssignedToUserId { get; set; }
        public Nullable<int> AssignedToDepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual User User1 { get; set; }
    }
}
