//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufactureProduct
    {
        public int Id { get; set; }
        public int ManufactureId { get; set; }
        public bool ProposedOrProduction { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int PackageId { get; set; }
        public bool InOut { get; set; }
        public Nullable<decimal> CostRate { get; set; }
        public Nullable<decimal> BuildRate { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
    }
}
