//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufactureDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManufactureDepartment()
        {
            this.ManufactureDepartmentProducts = new HashSet<ManufactureDepartmentProduct>();
            this.ManufactureDepartmentUsers = new HashSet<ManufactureDepartmentUser>();
        }
    
        public int Id { get; set; }
        public int ManufactureId { get; set; }
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public bool IsVendor { get; set; }
        public Nullable<int> HeadUserId { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<int> StartedByUserId { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public Nullable<int> CompletedByUserId { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public Nullable<int> CancelledByUserId { get; set; }
        public string Remarks { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufactureDepartmentProduct> ManufactureDepartmentProducts { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufactureDepartmentUser> ManufactureDepartmentUsers { get; set; }
    }
}
