//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Orders1 = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> ParentOrderId { get; set; }
        public int LotNumber { get; set; }
        public decimal TotalAmount { get; set; }
        public string Note { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> DueDays { get; set; }
        public bool IsVoid { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool IsReceiptGenerated { get; set; }
        public Nullable<System.DateTime> ReceiptGeneratedDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal DiscountAmount { get; set; }
        public string PaymentType { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<System.DateTime> PaymentCompleteDate { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string SupplierInvoice { get; set; }
        public string VatNumber { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ToWarehouseId { get; set; }
        public Nullable<decimal> CostPriceTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
