//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.InventoryUnits = new HashSet<InventoryUnit>();
            this.TransactionItems = new HashSet<TransactionItem>();
            this.TransactionItems1 = new HashSet<TransactionItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public decimal UnitQuantity { get; set; }
        public decimal PackageQuantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Total { get; set; }
        public decimal NetWeight { get; set; }
        public decimal GrossWeight { get; set; }
        public bool IsReceived { get; set; }
        public bool IsHold { get; set; }
        public int LotNumber { get; set; }
        public string Reference { get; set; }
        public string Adjustment { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> CostPriceRate { get; set; }
        public Nullable<decimal> CostPriceTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryUnit> InventoryUnits { get; set; }
        public virtual Order Order { get; set; }
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionItem> TransactionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionItem> TransactionItems1 { get; set; }
    }
}
