//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public System.DateTime Date { get; set; }
        public string PriceType { get; set; }
        public Nullable<int> PackageId { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
    }
}
