//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionItem
    {
        public int Id { get; set; }
        public int TransactionId { get; set; }
        public Nullable<int> PurchaseOrderItemId { get; set; }
        public decimal UnitQuantity { get; set; }
        public Nullable<int> SaleOrderItemId { get; set; }
        public decimal CostPriceRate { get; set; }
        public decimal CostPriceTotal { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual OrderItem OrderItem1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
