//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManufacture
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ManufactureDepartmentUserId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public bool InOut { get; set; }
        public Nullable<decimal> BuildRate { get; set; }
        public string Remarks { get; set; }
        public int PackageId { get; set; }
    
        public virtual ManufactureDepartmentUser ManufactureDepartmentUser { get; set; }
        public virtual Package Package { get; set; }
        public virtual Product Product { get; set; }
    }
}
