// <auto-generated />
namespace Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WarehouseId_is_now_nullable_in_OrderItem_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WarehouseId_is_now_nullable_in_OrderItem_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202002051927247_WarehouseId_is_now_nullable_in_OrderItem_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
