// <auto-generated />
namespace Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class precisionOfUOMQuantityChangedTo18_9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(precisionOfUOMQuantityChangedTo18_9));
        
        string IMigrationMetadata.Id
        {
            get { return "202105091903145_precisionOfUOMQuantityChangedTo18_9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
